/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.types.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PosInvoice extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2661141816802863804L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PosInvoice\",\"namespace\":\"com.example.types.avro\",\"fields\":[{\"name\":\"DateTime\",\"type\":[\"null\",\"long\"],\"default\":null,\"logicalType\":\"timestamp-millis\"},{\"name\":\"StoreID\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"PosID\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"CustomerType\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"DeliveryType\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"ItemsCostList\",\"type\":{\"type\":\"array\",\"items\":\"int\"},\"default\":null},{\"name\":\"NumberOfItems\",\"type\":[\"null\",\"int\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Long DateTime;
  @Deprecated public java.lang.CharSequence StoreID;
  @Deprecated public java.lang.CharSequence PosID;
  @Deprecated public java.lang.CharSequence CustomerType;
  @Deprecated public java.lang.CharSequence DeliveryType;
  @Deprecated public java.util.List<java.lang.Integer> ItemsCostList;
  @Deprecated public java.lang.Integer NumberOfItems;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PosInvoice() {}

  /**
   * All-args constructor.
   * @param DateTime The new value for DateTime
   * @param StoreID The new value for StoreID
   * @param PosID The new value for PosID
   * @param CustomerType The new value for CustomerType
   * @param DeliveryType The new value for DeliveryType
   * @param ItemsCostList The new value for ItemsCostList
   * @param NumberOfItems The new value for NumberOfItems
   */
  public PosInvoice(java.lang.Long DateTime, java.lang.CharSequence StoreID, java.lang.CharSequence PosID, java.lang.CharSequence CustomerType, java.lang.CharSequence DeliveryType, java.util.List<java.lang.Integer> ItemsCostList, java.lang.Integer NumberOfItems) {
    this.DateTime = DateTime;
    this.StoreID = StoreID;
    this.PosID = PosID;
    this.CustomerType = CustomerType;
    this.DeliveryType = DeliveryType;
    this.ItemsCostList = ItemsCostList;
    this.NumberOfItems = NumberOfItems;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return DateTime;
    case 1: return StoreID;
    case 2: return PosID;
    case 3: return CustomerType;
    case 4: return DeliveryType;
    case 5: return ItemsCostList;
    case 6: return NumberOfItems;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: DateTime = (java.lang.Long)value$; break;
    case 1: StoreID = (java.lang.CharSequence)value$; break;
    case 2: PosID = (java.lang.CharSequence)value$; break;
    case 3: CustomerType = (java.lang.CharSequence)value$; break;
    case 4: DeliveryType = (java.lang.CharSequence)value$; break;
    case 5: ItemsCostList = (java.util.List<java.lang.Integer>)value$; break;
    case 6: NumberOfItems = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'DateTime' field.
   * @return The value of the 'DateTime' field.
   */
  public java.lang.Long getDateTime() {
    return DateTime;
  }

  /**
   * Sets the value of the 'DateTime' field.
   * @param value the value to set.
   */
  public void setDateTime(java.lang.Long value) {
    this.DateTime = value;
  }

  /**
   * Gets the value of the 'StoreID' field.
   * @return The value of the 'StoreID' field.
   */
  public java.lang.CharSequence getStoreID() {
    return StoreID;
  }

  /**
   * Sets the value of the 'StoreID' field.
   * @param value the value to set.
   */
  public void setStoreID(java.lang.CharSequence value) {
    this.StoreID = value;
  }

  /**
   * Gets the value of the 'PosID' field.
   * @return The value of the 'PosID' field.
   */
  public java.lang.CharSequence getPosID() {
    return PosID;
  }

  /**
   * Sets the value of the 'PosID' field.
   * @param value the value to set.
   */
  public void setPosID(java.lang.CharSequence value) {
    this.PosID = value;
  }

  /**
   * Gets the value of the 'CustomerType' field.
   * @return The value of the 'CustomerType' field.
   */
  public java.lang.CharSequence getCustomerType() {
    return CustomerType;
  }

  /**
   * Sets the value of the 'CustomerType' field.
   * @param value the value to set.
   */
  public void setCustomerType(java.lang.CharSequence value) {
    this.CustomerType = value;
  }

  /**
   * Gets the value of the 'DeliveryType' field.
   * @return The value of the 'DeliveryType' field.
   */
  public java.lang.CharSequence getDeliveryType() {
    return DeliveryType;
  }

  /**
   * Sets the value of the 'DeliveryType' field.
   * @param value the value to set.
   */
  public void setDeliveryType(java.lang.CharSequence value) {
    this.DeliveryType = value;
  }

  /**
   * Gets the value of the 'ItemsCostList' field.
   * @return The value of the 'ItemsCostList' field.
   */
  public java.util.List<java.lang.Integer> getItemsCostList() {
    return ItemsCostList;
  }

  /**
   * Sets the value of the 'ItemsCostList' field.
   * @param value the value to set.
   */
  public void setItemsCostList(java.util.List<java.lang.Integer> value) {
    this.ItemsCostList = value;
  }

  /**
   * Gets the value of the 'NumberOfItems' field.
   * @return The value of the 'NumberOfItems' field.
   */
  public java.lang.Integer getNumberOfItems() {
    return NumberOfItems;
  }

  /**
   * Sets the value of the 'NumberOfItems' field.
   * @param value the value to set.
   */
  public void setNumberOfItems(java.lang.Integer value) {
    this.NumberOfItems = value;
  }

  /**
   * Creates a new PosInvoice RecordBuilder.
   * @return A new PosInvoice RecordBuilder
   */
  public static com.example.types.avro.PosInvoice.Builder newBuilder() {
    return new com.example.types.avro.PosInvoice.Builder();
  }

  /**
   * Creates a new PosInvoice RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PosInvoice RecordBuilder
   */
  public static com.example.types.avro.PosInvoice.Builder newBuilder(com.example.types.avro.PosInvoice.Builder other) {
    return new com.example.types.avro.PosInvoice.Builder(other);
  }

  /**
   * Creates a new PosInvoice RecordBuilder by copying an existing PosInvoice instance.
   * @param other The existing instance to copy.
   * @return A new PosInvoice RecordBuilder
   */
  public static com.example.types.avro.PosInvoice.Builder newBuilder(com.example.types.avro.PosInvoice other) {
    return new com.example.types.avro.PosInvoice.Builder(other);
  }

  /**
   * RecordBuilder for PosInvoice instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PosInvoice>
    implements org.apache.avro.data.RecordBuilder<PosInvoice> {

    private java.lang.Long DateTime;
    private java.lang.CharSequence StoreID;
    private java.lang.CharSequence PosID;
    private java.lang.CharSequence CustomerType;
    private java.lang.CharSequence DeliveryType;
    private java.util.List<java.lang.Integer> ItemsCostList;
    private java.lang.Integer NumberOfItems;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.types.avro.PosInvoice.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.DateTime)) {
        this.DateTime = data().deepCopy(fields()[0].schema(), other.DateTime);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.StoreID)) {
        this.StoreID = data().deepCopy(fields()[1].schema(), other.StoreID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.PosID)) {
        this.PosID = data().deepCopy(fields()[2].schema(), other.PosID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.CustomerType)) {
        this.CustomerType = data().deepCopy(fields()[3].schema(), other.CustomerType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.DeliveryType)) {
        this.DeliveryType = data().deepCopy(fields()[4].schema(), other.DeliveryType);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.ItemsCostList)) {
        this.ItemsCostList = data().deepCopy(fields()[5].schema(), other.ItemsCostList);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.NumberOfItems)) {
        this.NumberOfItems = data().deepCopy(fields()[6].schema(), other.NumberOfItems);
        fieldSetFlags()[6] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PosInvoice instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.types.avro.PosInvoice other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.DateTime)) {
        this.DateTime = data().deepCopy(fields()[0].schema(), other.DateTime);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.StoreID)) {
        this.StoreID = data().deepCopy(fields()[1].schema(), other.StoreID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.PosID)) {
        this.PosID = data().deepCopy(fields()[2].schema(), other.PosID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.CustomerType)) {
        this.CustomerType = data().deepCopy(fields()[3].schema(), other.CustomerType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.DeliveryType)) {
        this.DeliveryType = data().deepCopy(fields()[4].schema(), other.DeliveryType);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.ItemsCostList)) {
        this.ItemsCostList = data().deepCopy(fields()[5].schema(), other.ItemsCostList);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.NumberOfItems)) {
        this.NumberOfItems = data().deepCopy(fields()[6].schema(), other.NumberOfItems);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'DateTime' field.
      * @return The value.
      */
    public java.lang.Long getDateTime() {
      return DateTime;
    }

    /**
      * Sets the value of the 'DateTime' field.
      * @param value The value of 'DateTime'.
      * @return This builder.
      */
    public com.example.types.avro.PosInvoice.Builder setDateTime(java.lang.Long value) {
      validate(fields()[0], value);
      this.DateTime = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'DateTime' field has been set.
      * @return True if the 'DateTime' field has been set, false otherwise.
      */
    public boolean hasDateTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'DateTime' field.
      * @return This builder.
      */
    public com.example.types.avro.PosInvoice.Builder clearDateTime() {
      DateTime = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'StoreID' field.
      * @return The value.
      */
    public java.lang.CharSequence getStoreID() {
      return StoreID;
    }

    /**
      * Sets the value of the 'StoreID' field.
      * @param value The value of 'StoreID'.
      * @return This builder.
      */
    public com.example.types.avro.PosInvoice.Builder setStoreID(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.StoreID = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'StoreID' field has been set.
      * @return True if the 'StoreID' field has been set, false otherwise.
      */
    public boolean hasStoreID() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'StoreID' field.
      * @return This builder.
      */
    public com.example.types.avro.PosInvoice.Builder clearStoreID() {
      StoreID = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'PosID' field.
      * @return The value.
      */
    public java.lang.CharSequence getPosID() {
      return PosID;
    }

    /**
      * Sets the value of the 'PosID' field.
      * @param value The value of 'PosID'.
      * @return This builder.
      */
    public com.example.types.avro.PosInvoice.Builder setPosID(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.PosID = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'PosID' field has been set.
      * @return True if the 'PosID' field has been set, false otherwise.
      */
    public boolean hasPosID() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'PosID' field.
      * @return This builder.
      */
    public com.example.types.avro.PosInvoice.Builder clearPosID() {
      PosID = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'CustomerType' field.
      * @return The value.
      */
    public java.lang.CharSequence getCustomerType() {
      return CustomerType;
    }

    /**
      * Sets the value of the 'CustomerType' field.
      * @param value The value of 'CustomerType'.
      * @return This builder.
      */
    public com.example.types.avro.PosInvoice.Builder setCustomerType(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.CustomerType = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'CustomerType' field has been set.
      * @return True if the 'CustomerType' field has been set, false otherwise.
      */
    public boolean hasCustomerType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'CustomerType' field.
      * @return This builder.
      */
    public com.example.types.avro.PosInvoice.Builder clearCustomerType() {
      CustomerType = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'DeliveryType' field.
      * @return The value.
      */
    public java.lang.CharSequence getDeliveryType() {
      return DeliveryType;
    }

    /**
      * Sets the value of the 'DeliveryType' field.
      * @param value The value of 'DeliveryType'.
      * @return This builder.
      */
    public com.example.types.avro.PosInvoice.Builder setDeliveryType(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.DeliveryType = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'DeliveryType' field has been set.
      * @return True if the 'DeliveryType' field has been set, false otherwise.
      */
    public boolean hasDeliveryType() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'DeliveryType' field.
      * @return This builder.
      */
    public com.example.types.avro.PosInvoice.Builder clearDeliveryType() {
      DeliveryType = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'ItemsCostList' field.
      * @return The value.
      */
    public java.util.List<java.lang.Integer> getItemsCostList() {
      return ItemsCostList;
    }

    /**
      * Sets the value of the 'ItemsCostList' field.
      * @param value The value of 'ItemsCostList'.
      * @return This builder.
      */
    public com.example.types.avro.PosInvoice.Builder setItemsCostList(java.util.List<java.lang.Integer> value) {
      validate(fields()[5], value);
      this.ItemsCostList = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'ItemsCostList' field has been set.
      * @return True if the 'ItemsCostList' field has been set, false otherwise.
      */
    public boolean hasItemsCostList() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'ItemsCostList' field.
      * @return This builder.
      */
    public com.example.types.avro.PosInvoice.Builder clearItemsCostList() {
      ItemsCostList = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'NumberOfItems' field.
      * @return The value.
      */
    public java.lang.Integer getNumberOfItems() {
      return NumberOfItems;
    }

    /**
      * Sets the value of the 'NumberOfItems' field.
      * @param value The value of 'NumberOfItems'.
      * @return This builder.
      */
    public com.example.types.avro.PosInvoice.Builder setNumberOfItems(java.lang.Integer value) {
      validate(fields()[6], value);
      this.NumberOfItems = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'NumberOfItems' field has been set.
      * @return True if the 'NumberOfItems' field has been set, false otherwise.
      */
    public boolean hasNumberOfItems() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'NumberOfItems' field.
      * @return This builder.
      */
    public com.example.types.avro.PosInvoice.Builder clearNumberOfItems() {
      NumberOfItems = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public PosInvoice build() {
      try {
        PosInvoice record = new PosInvoice();
        record.DateTime = fieldSetFlags()[0] ? this.DateTime : (java.lang.Long) defaultValue(fields()[0]);
        record.StoreID = fieldSetFlags()[1] ? this.StoreID : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.PosID = fieldSetFlags()[2] ? this.PosID : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.CustomerType = fieldSetFlags()[3] ? this.CustomerType : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.DeliveryType = fieldSetFlags()[4] ? this.DeliveryType : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.ItemsCostList = fieldSetFlags()[5] ? this.ItemsCostList : (java.util.List<java.lang.Integer>) defaultValue(fields()[5]);
        record.NumberOfItems = fieldSetFlags()[6] ? this.NumberOfItems : (java.lang.Integer) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
